<?php

declare(strict_types=1);

/*
 * BİA (bia360.biaoperasyonel.com) ile otopark-modulu-kullanim.md karşılaştırması.
 * "sistem" alanı bu projenin şu anki davranışıdır; madde kodları karar kayıtlarının anahtarıdır, değiştirilmemelidir.
 */

return [
    'kaynaklar' => [
        'bia' => 'BİA 360 Yönetim Paneli (bayi hesabıyla, salt okunur tarama)',
        'md' => 'otopark-modulu-kullanim.md (Otopark Modülü Kullanım Rehberi)',
        'sistem' => 'Bu proje (BİA akışına göre kuruldu)',
    ],

    'ozet' => [
        'İki kaynak aynı işi (başkasına ait araçları bir alanda tutup hizmet vermek) farklı bakış açılarıyla anlatıyor.',
        'BİA "stok ve maliyet" mantığıyla çalışır: araç stoğa girer, stoktayken gün ve ek hizmetler birikir, dönem sonunda depolama ve ek hizmet raporlarıyla firmaya faturalanır.',
        'MD "otopark ve tutanak" mantığıyla çalışır: araç önce kaydedilir, teslim alma formu ile otoparka girer, teslim etme formu ile çıkar; her giriş ve çıkışta imzalı tutanak (PDF) oluşur ve ücret çıkışta gün × tarife olarak hesaplanır.',
        'Müşterinin takıldığı yerler büyük ölçüde sözcüklerden (Otopark ↔ Lokasyon, Tarife ↔ Depolama Fiyatı, Teslim Alma ↔ Stoğa Giriş) ve durum akışından (Beklemede/Otoparkta/Müsait/Teslim Edildi ↔ Stokta/Stoktan Çıktı) kaynaklanıyor.',
        'Şu anki sistem tamamen BİA sözcükleri ve akışıyla çalışıyor. MD\'ye özgü özellikler (kapasite, imzalı tutanak, ön hesaplama kartı, müşteri kullanıcısı) henüz yok; aşağıdaki maddelerden karar verilerek eklenebilir.',
    ],

    'sozluk' => [
        ['md' => 'Otopark', 'bia' => 'Lokasyon (Bayi)', 'not' => 'BİA\'da her bayi bir lokasyondur; ayrıca Lokasyon Türü (Açık/Kapalı) ve Lokasyon Detay alanları var.'],
        ['md' => 'Tarife', 'bia' => 'Depolama Fiyatı (günlük)', 'not' => 'Firma + lokasyon + araç tipine göre tanımlanır, girişte seçilmez, otomatik uygulanır.'],
        ['md' => 'Teslim Alma (Check-in)', 'bia' => 'Stoğa Giriş / Giriş Hareketi', 'not' => 'BİA\'da "Hızlı Araç Ekle" veya "Araç Ekle" formunda Hareket Tipi = Giriş.'],
        ['md' => 'Teslim Etme (Check-out)', 'bia' => 'Stoktan Çıkar / Çıkış Hareketi', 'not' => 'Stoktaki Araçlar listesinden yapılır.'],
        ['md' => 'Otoparkta (durum)', 'bia' => 'Stokta', 'not' => 'Stoktaki Araçlar listesinde görünür.'],
        ['md' => 'Teslim Edildi (durum)', 'bia' => 'Stoktan Çıkan', 'not' => 'Stoktan Çıkanlar listesinde görünür.'],
        ['md' => 'Beklemede / Müsait (durum)', 'bia' => '— (karşılığı yok)', 'not' => 'BİA\'da "Araç Durumu" Sıfır / İkinci El demektir, park durumu değildir.'],
        ['md' => 'VIN', 'bia' => 'Şasi Numarası (Şase)', 'not' => 'BİA\'da aracın benzersiz anahtarı şasidir.'],
        ['md' => 'Park yeri', 'bia' => 'Park Kodu / Lokasyon Detay', 'not' => ''],
        ['md' => 'Teslim Formu / Tutanak (handover_form)', 'bia' => 'Tesellüm Formu', 'not' => 'BİA\'da araç bazlı yazdırılır; ayrı tutanak listesi yok.'],
        ['md' => 'Giriş-Çıkış Kayıtları', 'bia' => 'Araç Hareketleri (Stoktaki Araçlar + Stoktan Çıkanlar)', 'not' => 'BİA iki ayrı liste kullanır.'],
        ['md' => 'Müşteriler / Otopark Bayileri', 'bia' => 'Firma (Müşteri) ve Bayi (Lokasyon)', 'not' => 'BİA\'da ikisi farklı kavram: firma aracın sahibi, bayi aracın durduğu yer.'],
        ['md' => 'Yapılan İşlemler', 'bia' => 'Ek Hizmet / Ek Maliyet (Maliyet Tipi)', 'not' => 'BİA\'da her işlem tutarıyla araç ekstresine yazılır.'],
        ['md' => 'Gün sayısı', 'bia' => 'Depolama Süresi', 'not' => ''],
        ['md' => 'Toplam tutar', 'bia' => 'Depolama Tutarı + Ek Hizmet Tutarı', 'not' => 'BİA\'da iki ayrı raporda çıkar.'],
        ['md' => 'Doluluk raporu', 'bia' => 'Anlık Stok (dashboard)', 'not' => 'BİA\'da kapasite olmadığı için doluluk oranı yok.'],
        ['md' => 'Müşteri Araçlarım', 'bia' => '— (bayi hesabıyla görülmedi)', 'not' => 'BİA\'da "Müşteri" kullanıcı grubu tanımlı ama menüsü taramada görünmedi.'],
    ],

    'akis' => [
        'bia' => [
            ['baslik' => 'Araç gelir, stoğa alınır', 'detay' => '"Hızlı Araç Ekle" (veya Araç Ekle / Toplu Stok Girişi) formunda şasi, plaka, araç tipi, firma, lokasyon, teslim eden/alan, envanter girilir. Araç kaydı ve Giriş hareketi aynı anda oluşur.'],
            ['baslik' => 'Etiket ve tesellüm', 'detay' => 'QR etiket basılır, istenirse tesellüm formu yazdırılır.'],
            ['baslik' => 'Stokta bekler', 'detay' => '"Stoktaki Araçlar" listesinde görünür, Depolama Süresi her gün artar.'],
            ['baslik' => 'Ek hizmetler yazılır', 'detay' => 'Yıkama, hazırlık, taşıma gibi işler "Hızlı Maliyet Ekle", "Toplu Ek Maliyet Girişi" veya tamamlanan İş Emri ile araç ekstresine yazılır.'],
            ['baslik' => 'Stoktan çıkar', 'detay' => '"Stoktan Çıkar" ile hareket nedeni, sevkiyat tipi/durumu ve teslim alan girilir; araç "Stoktan Çıkanlar"a düşer.'],
            ['baslik' => 'Dönem sonu faturalama', 'detay' => '"Depolama Raporu" (tarih aralığında gün × günlük fiyat) ve "Ek Hizmetler Raporu" ile firmaya faturalanacak tutar çıkar.'],
        ],
        'md' => [
            ['baslik' => 'Otopark ve tarife tanımlanır', 'detay' => 'Otoparklar (kapasite) ve Tarifeler (günlük fiyat) önceden girilir.'],
            ['baslik' => 'Araç kaydedilir', 'detay' => 'Araçlar > Yeni Araç: plaka, VIN, marka, model, yıl, otopark. Kapasite doluysa sistem uyarır. Durum: Beklemede.'],
            ['baslik' => '(Müşteri) otoparka gönderir', 'detay' => 'Müşteri kullanıcısı "Müşteri Araçlarım"dan "Otoparka Gönder" der.'],
            ['baslik' => 'Teslim Alma formu', 'detay' => 'Araç + otopark + tarife seçilir; tarih, km, teslim alan, kaporta/iç trim/lastik kontrol kartları, fotoğraf, imza. Park kaydı ve teslim alma tutanağı oluşur. Durum: Otoparkta.'],
            ['baslik' => 'Teslime hazır', 'detay' => 'Durum "Müsait" yapılır (listeden Gönder/Çıkar butonları).'],
            ['baslik' => 'Teslim Etme formu', 'detay' => 'Giriş kaydı seçilir, ön hesaplama kartı gün ve toplam tutarı gösterir; km, alıcı, yapılan işlemler, imza. Park kaydı kapanır, teslim etme tutanağı oluşur, detay sayfasına gider. Durum: Teslim Edildi.'],
            ['baslik' => 'Tutanak ve rapor', 'detay' => 'Teslim Formları listesinden PDF indirilir; Otopark Durum Raporu incelenir.'],
        ],
    ],

    'kategoriler' => [
        'kavram' => 'Temel kavramlar',
        'arac' => 'Araç kaydı',
        'giris' => 'Giriş (Teslim Alma)',
        'cikis' => 'Çıkış (Teslim Etme)',
        'ucret' => 'Ücret ve faturalama',
        'form' => 'Tutanak / form / PDF',
        'rapor' => 'Liste ve raporlar',
        'yetki' => 'Kullanıcılar ve yetki',
        'bia_ek' => 'Sadece BİA\'da olanlar',
    ],

    'turler' => [
        'terim' => ['Sözcük farkı', 'info'],
        'akis' => ['Akış farkı', 'warning'],
        'md_ozellik' => ['MD\'de var, BİA\'da yok', 'danger'],
        'bia_ozellik' => ['BİA\'da var, MD\'de yok', 'primary'],
        'ayni' => ['Aynı / uyumlu', 'success'],
    ],

    'kararlar' => [
        'bekliyor' => ['Karar bekliyor', 'secondary'],
        'bia' => ['BİA gibi kalsın', 'primary'],
        'md' => ['MD\'ye göre değişecek', 'warning'],
        'birlestir' => ['İkisi birleştirilecek', 'info'],
        'yapildi' => ['Değişiklik yapıldı', 'success'],
        'gerek_yok' => ['Gerek yok', 'dark'],
    ],

    'maddeler' => [
        // Temel kavramlar
        ['kod' => 'K01', 'kategori' => 'kavram', 'tur' => 'terim', 'baslik' => 'Ana kavram: Stok mu, Otopark mı?',
            'bia' => 'Her şey "stok" üzerinden anlatılır: araç stoğa girer, stokta kalır, stoktan çıkar. Menü ve başlıklar: Stoktaki Araçlar, Stoktan Çıkanlar, Anlık Stok.',
            'md' => 'Her şey "otopark" ve "park kaydı" üzerinden anlatılır: araç otoparka teslim alınır, otoparkta durur, teslim edilir.',
            'sistem' => 'BİA sözcükleri kullanılıyor (Stoktaki Araçlar / Stoktan Çıkanlar).', 'url' => '/arac_hareketleri/giris'],
        ['kod' => 'K02', 'kategori' => 'kavram', 'tur' => 'terim', 'baslik' => 'Otopark ↔ Lokasyon',
            'bia' => 'Aracın durduğu yer "Lokasyon"dur ve bir bayiye karşılık gelir (ör. BİA ANKARA). Ek olarak Lokasyon Türü (Açık / Kapalı / Her İkisi De) ve serbest metin Lokasyon Detay var.',
            'md' => '"Otoparklar" menüsünde otopark listesi, her otoparkın kapasitesi ve bilgileri düzenlenir.',
            'sistem' => 'Lokasyon = Bayi tanımı (Tanımlar > Bayiler). Ayrı bir "Otopark" tanımı ve kapasite alanı yok.', 'url' => '/arac_yonetimi/tanimlar/bayiler'],
        ['kod' => 'K03', 'kategori' => 'kavram', 'tur' => 'terim', 'baslik' => 'Müşteri ve bayi ayrımı',
            'bia' => 'Firma (Müşteri) aracın sahibidir (ör. DOĞUŞ OTO); Bayi ise aracın bulunduğu lokasyonu işleten taraftır. Bayi kullanıcıları yalnızca kendi lokasyonlarını görür.',
            'md' => '"Müşteriler / Otopark Bayileri" tek menüde "iş ortakları" olarak anılır; ayrım net değil.',
            'sistem' => 'BİA gibi: Müşteriler ve Bayiler ayrı tanımlar, bayi kullanıcısı lokasyonla sınırlı.', 'url' => '/arac_yonetimi/tanimlar/musteriler'],
        ['kod' => 'K04', 'kategori' => 'kavram', 'tur' => 'md_ozellik', 'baslik' => 'Otopark kapasitesi',
            'bia' => 'Kapasite kavramı yok; bir lokasyona sınırsız araç girilebilir.',
            'md' => 'Araç eklerken kapasite doluysa "Bu otoparkta yer kalmamıştır" uyarısı çıkar; başka otopark seçilir veya kapasite artırılır.',
            'sistem' => 'Kapasite kontrolü yok (BİA gibi).', 'url' => null],

        // Araç kaydı
        ['kod' => 'A01', 'kategori' => 'arac', 'tur' => 'akis', 'baslik' => 'Araç kaydı ile girişin ilişkisi',
            'bia' => 'Araç kaydı ve stoğa giriş aynı formda, tek adımda yapılır (Hızlı Araç Ekle: araç bilgileri + hareket bilgileri). Şasi daha önce kayıtlıysa mevcut araç güncellenip yeni giriş hareketi eklenir.',
            'md' => 'Önce "Araçlar > Yeni Araç" ile araç kaydedilir (durum Beklemede), sonra ayrı bir "Teslim Alma" formu ile otoparka alınır.',
            'sistem' => 'BİA gibi tek adım. "Araç Ekle" sayfasında hareket bölümü boş bırakılırsa araç stoğa alınmadan da kaydedilebiliyor.', 'url' => '/arac_yonetimi/ekle'],
        ['kod' => 'A02', 'kategori' => 'arac', 'tur' => 'terim', 'baslik' => 'VIN ↔ Şasi Numarası',
            'bia' => 'Alan adı "Şasi Numarası *"; aracın benzersiz anahtarıdır, listelerde "Şase" sütunu.',
            'md' => 'Formda "VIN" olarak geçer.',
            'sistem' => '"Şasi Numarası" kullanılıyor.', 'url' => null],
        ['kod' => 'A03', 'kategori' => 'arac', 'tur' => 'bia_ozellik', 'baslik' => 'Araç formundaki alanlar',
            'bia' => 'Zorunlu: şasi, plaka, araç durumu (Sıfır/İkinci El), araç tipi, kasa tipi, renk, marka, seri. Ayrıca model, model yılı, motor hacmi/gücü, yakıt, vites, KM, yakıt durumu, park kodu, önceki plaka, donanım listesi (güvenlik/iç/dış), araç envanteri, fotoğraflar ve kayıt belgeleri.',
            'md' => 'Plaka, VIN, marka, model, yıl ve otopark.',
            'sistem' => 'BİA\'daki tüm alanlar var.', 'url' => '/arac_yonetimi/ekle'],
        ['kod' => 'A04', 'kategori' => 'arac', 'tur' => 'akis', 'baslik' => 'Araç durumları',
            'bia' => 'Park durumu yalnızca "Stokta" / "Stoktan çıktı" (son hareket tipi Giriş / Çıkış). "Araç Durumu" alanı Sıfır / İkinci El anlamına gelir, park durumu değildir.',
            'md' => 'Dört durum: Beklemede (henüz park edilmedi), Otoparkta, Müsait (teslime hazır), Teslim Edildi. Listeden "Gönder" / "Çıkar" butonlarıyla değiştirilir.',
            'sistem' => 'BİA gibi: stokta / stoktan çıktı. Beklemede ve Müsait durumları yok.', 'url' => '/arac_yonetimi'],
        ['kod' => 'A05', 'kategori' => 'arac', 'tur' => 'terim', 'baslik' => 'Park yeri',
            'bia' => '"Park Kodu" (araç kaydında) ve "Lokasyon Detay" (hareket kaydında, ör. Blok A-12).',
            'md' => 'Araç güncellemede "park yeri" değiştirilir.',
            'sistem' => 'Park Kodu ve Lokasyon Detay alanları var; toplu lokasyon güncelleme de var.', 'url' => '/arac_yonetimi/toplu_kayit_guncelleme_lokasyon'],

        // Giriş
        ['kod' => 'G01', 'kategori' => 'giris', 'tur' => 'terim', 'baslik' => 'Giriş formunun adı ve yeri',
            'bia' => 'Üst bardaki "Hızlı Araç Ekle" butonu veya Araç Yönetimi > Araç Ekle; toplu için Toplu Stok Girişi (Excel).',
            'md' => 'Soldaki "Teslim Alma" menüsü, açılan form "Araç Girişi".',
            'sistem' => 'BİA gibi: Hızlı Araç Ekle (her sayfada), Araç Ekle, Toplu Stok Girişi.', 'url' => '/arac_yonetimi/toplu_stok_girisi'],
        ['kod' => 'G02', 'kategori' => 'giris', 'tur' => 'bia_ozellik', 'baslik' => 'Giriş bilgileri',
            'bia' => 'Hareket Tipi (Giriş/Çıkış), Hareket Nedeni (Sevk / Müşteri / Vale / Servis teslimatı, Servis iadesi), Müşteri, Lokasyon Türü, Lokasyon, Lokasyon Detay, Teslim Eden (ad, telefon, e-posta), Teslim Alan (ad, telefon, e-posta), Teslim Alan Personel, Hareket Tarihi + saat, açıklama.',
            'md' => 'Araç, otopark, giriş tarihi, kilometre, teslim alan bilgileri.',
            'sistem' => 'BİA\'daki tüm alanlar var.', 'url' => null],
        ['kod' => 'G03', 'kategori' => 'giris', 'tur' => 'md_ozellik', 'baslik' => 'Kontrol kartları (kaporta, iç trim, lastik...)',
            'bia' => 'Girişte yalnızca envanter onay kutuları (yedek anahtar, stepne, ruhsat, paspas...) ve donanım listesi var. Hasar/kontrol listesi yok; "Ekspertiz Yönetimi" ayrı bir modül (bayi hesabında içi boş).',
            'md' => 'Formda dikey kartlar halinde çok sayıda kontrol alanı (kaporta, iç trim, lastik vb.) tablet üzerinden sırayla doldurulur.',
            'sistem' => 'Envanter ve donanım var, kontrol kartları yok.', 'url' => null],
        ['kod' => 'G04', 'kategori' => 'giris', 'tur' => 'md_ozellik', 'baslik' => 'Fotoğraf ve imza',
            'bia' => 'Araç kaydına fotoğraf ve kayıt belgesi yüklenebilir; imza alanı yok.',
            'md' => 'Fotoğraf istenen yerlere dosya yüklenir; en altta imza görseli eklenir.',
            'sistem' => 'Fotoğraf ve belge yükleme var (araç düzenleme), imza yok.', 'url' => null],
        ['kod' => 'G05', 'kategori' => 'giris', 'tur' => 'akis', 'baslik' => 'Tarife seçimi',
            'bia' => 'Girişte fiyat seçilmez; firma + lokasyon + araç tipine göre tanımlı günlük depolama fiyatı raporda otomatik uygulanır.',
            'md' => 'Check-in sırasında tarife seçilir.',
            'sistem' => 'BİA gibi otomatik.', 'url' => '/arac_yonetimi/tanimlar/depolama_fiyatlari'],
        ['kod' => 'G06', 'kategori' => 'giris', 'tur' => 'ayni', 'baslik' => 'Aynı araç ikinci kez girilemez',
            'bia' => 'Stokta olan araç tekrar stoğa alınamaz.',
            'md' => '"Bu araç için aktif bir otopark giriş kaydı bulunuyor" mesajı; önce teslim etme yapılmalı.',
            'sistem' => 'Aynı kural var; mesaj: "... şasi numaralı araç zaten stokta." Başka lokasyonun stoğundaki araç için "Bu araç başka bir lokasyonun stoğunda."', 'url' => null],

        // Çıkış
        ['kod' => 'C01', 'kategori' => 'cikis', 'tur' => 'akis', 'baslik' => 'Çıkışın başlatıldığı yer',
            'bia' => '"Stoktaki Araçlar" listesinde aracın satırından "Stoktan Çıkar".',
            'md' => 'Ayrı "Teslim Etme" menüsü; açılan sayfada "Araç Giriş Kaydı" listesinden kayıt seçilir.',
            'sistem' => 'BİA gibi: Stoktaki Araçlar > Stoktan Çıkar.', 'url' => '/arac_hareketleri/giris'],
        ['kod' => 'C02', 'kategori' => 'cikis', 'tur' => 'md_ozellik', 'baslik' => 'Ön hesaplama kartı',
            'bia' => 'Çıkış formunda ücret gösterilmez; ücret dönem sonunda Depolama Raporu\'nda çıkar.',
            'md' => 'Araç seçilince kartta giriş/çıkış tarihi, gün sayısı ve toplam tutar otomatik hesaplanır; çıkış tarihi değişince yeniden hesaplanır.',
            'sistem' => 'Çıkış formunda kart yok. Aracın düzenleme sayfasındaki "Depolama" sekmesinde gün ve tutar görülebiliyor.', 'url' => null],
        ['kod' => 'C03', 'kategori' => 'cikis', 'tur' => 'terim', 'baslik' => 'Çıkış bilgileri',
            'bia' => 'Hareket Nedeni, Sevkiyat Tipi (Bireysel / Vale / Çekici), Sevkiyat Durumu (Bekliyor / Devam Ediyor / Tamamlandı), Teslim Alan bilgileri, Hareket Tarihi.',
            'md' => 'Kilometre, alıcı bilgileri, "Yapılan İşlemler", notlar, imza; buton adı "Çıkış Yap ve Tutanak Kaydet".',
            'sistem' => 'BİA alanları var; "Yapılan İşlemler" yerine ek hizmetler maliyet olarak ayrıca girilir. İmza ve çıkış KM\'si yok.', 'url' => null],
        ['kod' => 'C04', 'kategori' => 'cikis', 'tur' => 'akis', 'baslik' => 'Çıkış sonrası',
            'bia' => 'Araç "Stoktan Çıkanlar" listesine düşer.',
            'md' => 'Park kaydı kapanır, teslim etme tutanağı oluşur ve sistem "Giriş-Çıkış Detay" sayfasına yönlendirir.',
            'sistem' => 'BİA gibi. Hareket detay sayfası var ama otomatik yönlendirme ve tutanak yok.', 'url' => '/arac_hareketleri/cikis'],
        ['kod' => 'C05', 'kategori' => 'cikis', 'tur' => 'ayni', 'baslik' => 'Tarih kontrolü',
            'bia' => 'Taramada görülemedi (form gönderilmedi).',
            'md' => 'Belirtilmemiş.',
            'sistem' => 'Çıkış tarihi stoğa giriş tarihinden önce olamaz; stokta olmayan araç çıkarılamaz.', 'url' => null],

        // Ücret
        ['kod' => 'U01', 'kategori' => 'ucret', 'tur' => 'terim', 'baslik' => 'Tarife ↔ Depolama Fiyatı',
            'bia' => '"Depolama Fiyatı": firma + lokasyon + araç tipi başına günlük tutar (yönetici tanımlar).',
            'md' => '"Tarifeler" menüsü, "Yeni Tarife Ekle", günlük fiyat.',
            'sistem' => 'Tanımlar > Depolama Fiyatları (yönetici).', 'url' => '/arac_yonetimi/tanimlar/depolama_fiyatlari'],
        ['kod' => 'U02', 'kategori' => 'ucret', 'tur' => 'akis', 'baslik' => 'Ücretin hesaplandığı an',
            'bia' => 'Dönem bazlı: Depolama Raporu seçilen tarih aralığında her araç için başlangıç, bitiş, günlük fiyat, süre ve tutarı listeler (aylık faturalama).',
            'md' => 'Araç bazlı: çıkışta gün × tarife = toplam tutar.',
            'sistem' => 'BİA gibi Depolama Raporu; araç sayfasında da gün ve tutar görülebiliyor.', 'url' => '/depolama_raporu'],
        ['kod' => 'U03', 'kategori' => 'ucret', 'tur' => 'bia_ozellik', 'baslik' => 'Ek hizmet ücretleri',
            'bia' => 'Yıkama, hazırlık, teslim alma/etme, taşıma gibi her hizmet tutarıyla aracın ekstresine yazılır; Ek Hizmetler Raporu ile faturalanır.',
            'md' => 'Yalnızca çıkışta serbest metin "Yapılan İşlemler"; ücrete dahil değil.',
            'sistem' => 'BİA gibi: araç ekstresi, Hızlı Maliyet Ekle, Toplu Ek Maliyet, Ek Hizmetler Raporu.', 'url' => '/ek_hizmet_raporu'],

        // Form / PDF
        ['kod' => 'F01', 'kategori' => 'form', 'tur' => 'md_ozellik', 'baslik' => 'Teslim tutanakları',
            'bia' => 'Araç bazlı "Tesellüm Formu" yazdırılır; ayrıca kayıtlı bir tutanak listesi yok.',
            'md' => 'Her giriş ve çıkışta bir tutanak (handover_form) kaydı oluşur; "Teslim Formları" menüsünde listelenir, "Detay" ile açılır.',
            'sistem' => 'Tesellüm formu yazdırma var (araç sayfası). Tutanak kaydı ve listesi yok.', 'url' => null],
        ['kod' => 'F02', 'kategori' => 'form', 'tur' => 'md_ozellik', 'baslik' => 'PDF indirme',
            'bia' => 'QR etiketleri ve tesellüm formu PDF/yazdırma olarak alınır.',
            'md' => 'Tutanak detayında "PDF İndir" (Türkçe karakter destekli).',
            'sistem' => 'Tesellüm formu ve QR etiketleri yazdırma sayfası olarak açılır; tarayıcıdan PDF kaydedilebilir. Sunucuda üretilen PDF yok.', 'url' => null],
        ['kod' => 'F03', 'kategori' => 'form', 'tur' => 'bia_ozellik', 'baslik' => 'QR etiket',
            'bia' => 'Seçili araçlar için toplu QR etiket PDF\'i.',
            'md' => 'Yok.',
            'sistem' => 'Toplu QR etiket yazdırma var.', 'url' => null],

        // Rapor
        ['kod' => 'R01', 'kategori' => 'rapor', 'tur' => 'akis', 'baslik' => 'Giriş-çıkış listeleri',
            'bia' => 'İki ayrı liste: "Stoktaki Araçlar" (şase, plaka, firma, marka, seri, lokasyon, giriş tarihi, depolama süresi) ve "Stoktan Çıkanlar" (+ sevkiyat tipi/durumu).',
            'md' => 'Tek liste: "Giriş-Çıkış Kayıtları"; detayda araç, tarife, yapılan işlemler, tutanaklar ve PDF linkleri.',
            'sistem' => 'BİA gibi iki liste + hareket detay sayfası.', 'url' => '/arac_hareketleri/giris'],
        ['kod' => 'R02', 'kategori' => 'rapor', 'tur' => 'md_ozellik', 'baslik' => 'Otopark Durum Raporu',
            'bia' => 'Aynı adla bir rapor yok. Benzer bilgi Stoktaki Araçlar listesinde ve dashboardlarda (firma dağılımı, stok süre dağılımı).',
            'md' => 'Hangi müşteri/bayi hangi aracı getirdi, kim teslim aldı, araç yeni mi kullanılmış mı.',
            'sistem' => 'Ayrı rapor yok; listeler ve Excel çıktıları bu bilgileri içeriyor.', 'url' => null],
        ['kod' => 'R03', 'kategori' => 'rapor', 'tur' => 'bia_ozellik', 'baslik' => 'Dashboardlar',
            'bia' => 'Ana Dashboard (anlık stok, giriş/çıkış, maliyet, firma ve hizmet dağılımı, duyurular), Araç Yönetimi (Stok) Dashboard, İK Dashboard.',
            'md' => 'Ana ekranda yalnızca sol menü anlatılıyor.',
            'sistem' => 'Üç dashboard da var.', 'url' => '/'],

        // Yetki
        ['kod' => 'Y01', 'kategori' => 'yetki', 'tur' => 'md_ozellik', 'baslik' => 'Müşteri kullanıcısı ve "Müşteri Araçlarım"',
            'bia' => '"Müşteri" kullanıcı grubu tanımlı ama bayi hesabıyla ilgili menü görülmedi.',
            'md' => 'Müşteri kullanıcıları yalnızca kendi araçlarını görür ve "Otoparka Gönder" ile aracı otoparka gönderir.',
            'sistem' => 'Yalnızca Yönetici ve Bayi rolleri var; müşteri girişi yok.', 'url' => null],
        ['kod' => 'Y02', 'kategori' => 'yetki', 'tur' => 'ayni', 'baslik' => 'Şifre unutma',
            'bia' => 'Giriş ekranında şifre sıfırlama görülmedi.',
            'md' => 'Yöneticiden yeni şifre istenir.',
            'sistem' => 'Yönetici, Tanımlar > Kullanıcılar\'dan şifre değiştirir; kullanıcı Hesabım\'dan kendi şifresini değiştirir.', 'url' => '/kullanici/hesabim'],

        // Sadece BİA
        ['kod' => 'B01', 'kategori' => 'bia_ek', 'tur' => 'bia_ozellik', 'baslik' => 'İş emri yönetimi',
            'bia' => 'İş Emri Oluştur, Bekleyen / Tamamlanan İş Emri Talepleri; tamamlanan iş emri araçlara maliyet yazar.',
            'md' => 'Yok.', 'sistem' => 'Var.', 'url' => '/gorev_yonetimi'],
        ['kod' => 'B02', 'kategori' => 'bia_ek', 'tur' => 'bia_ozellik', 'baslik' => 'Saha operasyon iş takibi',
            'bia' => 'Girilen ek hizmetlerin (maliyetlerin) takip listesi.',
            'md' => 'Yok.', 'sistem' => 'Var.', 'url' => '/is_takibi'],
        ['kod' => 'B03', 'kategori' => 'bia_ek', 'tur' => 'bia_ozellik', 'baslik' => 'Toplu işlemler (Excel)',
            'bia' => 'Toplu stok girişi, toplu ek maliyet girişi, toplu lokasyon güncelleme; Excel çıktıları.',
            'md' => 'Yok.', 'sistem' => 'Var (CSV şablonu veya elle satır).', 'url' => '/arac_yonetimi/toplu_stok_girisi'],
        ['kod' => 'B04', 'kategori' => 'bia_ek', 'tur' => 'bia_ozellik', 'baslik' => 'Araç tanımları',
            'bia' => 'Marka, seri, model, renk, kasa/araç tipi, yakıt, vites, envanter, donanım, hareket nedeni tanımları.',
            'md' => 'Bahsedilmiyor.', 'sistem' => 'Var.', 'url' => '/arac_yonetimi/tanimlar'],
        ['kod' => 'B05', 'kategori' => 'bia_ek', 'tur' => 'bia_ozellik', 'baslik' => 'İK ve destek talepleri',
            'bia' => 'İK Dashboard, Destek Talepleri.',
            'md' => 'Yok.', 'sistem' => 'Var.', 'url' => '/destek_talepleri'],
        ['kod' => 'B06', 'kategori' => 'bia_ek', 'tur' => 'bia_ozellik', 'baslik' => 'İlan yönetimi (2. el satış)',
            'bia' => 'Stoktaki araçlar için "İlan Ekle", ilan performansı ve dashboard kartları görüldü.',
            'md' => 'Yok.', 'sistem' => 'Yok (otopark kapsamı dışında bırakıldı).', 'url' => null],
    ],
];
